language: node_js
node_js:
  - "7"
script:
  - npm run build
install:
  - npm install -g firebase-tools
  - npm install
  - sh -c 'cd functions && npm install'
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
